name: Validate build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
      
      - name: Configure environment
        run: |
          echo HOST={{ vars.HOST }} >> $GITHUB_ENV
          echo URL_POST_OFFICE_LIST={{ vars.URL_POST_OFFICE_LIST }} >> $GITHUB_ENV
          echo URL_POST_BOXES_LIST={{ vars.URL_POST_BOXES_LIST }} >> $GITHUB_ENV
          echo BATCH_SIZE={{ vars.BATCH_SIZE }} >> $GITHUB_ENV

      - name: Build project
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 5
          command: ./build.sh
